/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class MainView extends javax.swing.JFrame {
    
    private Controller controller; 
    //Nombre del cuadro de dialogo que se muestra al ejecutar el main
    private String appName;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        appName="Calcolatore";
        this.setTitle(appName);
        
        inputView1.mw = this;
        
        //Instrucciones para que la
        //aplicación finalice cuando se cierra la ventana principal de la aplicación.
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                controller.finish(0);
            }
        });
    }
    
    public void updateView(){
        stackView.updateView();
        varView.updateView();
        
        repaint();
    }
    
    public void setController(Controller c){
        controller = c;
    }
    
    public void recibeInput(String s){
        controller.inputHandler(s);
        this.updateView();
    }
    
    public void addToStack(String num){
        stackView.addNum(num);
    }
    
    public void removeFromStack(){
        stackView.removeNum();
    }
    
    public void cleanStack(){
        stackView.clean();
    }
    
    public void setVar(int i, String num){
        varView.setVariable(i, num);
    }
    
    public void setVar(char c, String num){
        varView.setVariable(c, num);
    }
    
    public void processBinaryOp(String result){
        this.stackView.removeNum();
        this.stackView.removeNum();
        this.stackView.addNum(result);
    }
    
    public void processUnaryOp(String result){
        this.stackView.removeNum();
        this.stackView.addNum(result);
    }
    
    public void drop(){
        this.stackView.removeNum();
    }
    
    public void dup(String result){
        this.stackView.addNum(result);
    }
    
    public void swap(String n1, String n2){
        this.stackView.removeNum();
        this.stackView.removeNum();
        this.stackView.addNum(n1);
        this.stackView.addNum(n2);
    }
    
    public void over(String n){
        
        this.stackView.addNum(n);
        
    }
    
    public void showView(){
        this.setVisible(true);
    }
    
    //Obtiene el nombre de la aplicación
    public String getAppName(){
        return appName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputView1 = new View.InputView();
        varView = new View.VariablesView();
        stackView = new View.StackView();
        infoView1 = new View.InfoView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputView1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varView, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stackView, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(infoView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(stackView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public boolean confirmExitMessage(){
        return (JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to exit?", 
                getAppName(), 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
    }
    
    public void InputErrorMessage(){
        if(this.isVisible())
        JOptionPane.showMessageDialog(this, 
                "The input is not correct. Please check the input", 
                getAppName(), 
                JOptionPane.ERROR_MESSAGE);
    }
    
    public void NoValueInStackToOperateMessage(){
        if(this.isVisible())
        JOptionPane.showMessageDialog(this, 
                "There is not enough values in the stack. Please introduce a value", 
                getAppName(), JOptionPane.ERROR_MESSAGE);
    }
    
    public void NoValueInVarToOperateMessage(){
        if(this.isVisible())
        JOptionPane.showMessageDialog(this, 
                "There is not a value in the var selected. Please introduce a value", 
                getAppName(), 
                JOptionPane.ERROR_MESSAGE);
    }
    
    public void CantDivideByZeroMessage(){
        if(this.isVisible())
        JOptionPane.showMessageDialog(this, 
                "Is not possible to divide by zero. Please introduce a different value", 
                getAppName(), JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.InfoView infoView1;
    private View.InputView inputView1;
    private View.StackView stackView;
    private View.VariablesView varView;
    // End of variables declaration//GEN-END:variables
}
