/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.GridLayout;
import java.util.ArrayList;

/**
 *
 * @author gabriel
 */
public class VariablesView extends javax.swing.JPanel {
    
    public final static int ROWS = 6;
    public final static int COLS = 6;
    
    ArrayList<varView> variables;
    
    /**
     * Creates new form StackView
     */
    public VariablesView() {
        initComponents();
        //DEBUG
        variables = new ArrayList<>();
        
        GridLayout g = new GridLayout(ROWS,COLS);
        this.setLayout(g);
        
        setUpVariables();
    }
    
    private void setUpVariables(){
        for(char name = 'a'; name <= 'z'; ++name){
            varView var = new varView();
            var.setName(Character.toString(name));
            var.setText(Character.toString(name));
            variables.add(var);
            add(var);
        }
    }
    
    public void setVariable(int i, String num){
        variables.get(i).setText(num);
    }
    
    public void setVariable(char c, String num){
        variables.get(c - 'a').setText(num);
    }
    
    public void updateView(){
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
