{
 "title": "JaimeCorzoGaldoAPI",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Tiempos de respuesta (JCG)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_bucket[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Heap (JCG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes\n", "legendFormat": "Heap Usada" },
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "Heap Total" }
   ]
  },
  {
   "title": "Uso CPU (JCG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"api-nodejs\"}[1m])\n\n",
     "legendFormat": "Uso de CPU"
    }
   ]
  }
 ]
}